name: advanced_app_manager
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  apk_admin: 2.2.4
  app_usage: ^2.0.0
  battery_indicator: ^0.1.0
  battery_info: ^1.0.8
  cool_alert: ^1.1.0
  cpu_reader: ^3.0.0
  cupertino_icons: ^1.0.3
  device_apps: ^2.1.1
  device_info: ^2.0.2
  equatable: ^2.0.3
  facebook_audience_network: 1.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  # google_mobile_ads: ^0.13.4
  hooks_riverpod: ^1.0.0-dev.7
  jiffy: ^4.1.0
  memory_info: ^0.0.2
  open_settings: ^2.0.2
  path_provider: ^2.0.4
  percent_indicator: ^3.4.0
  permission_handler: ^8.1.6
  platform: ^3.1.0
  share: ^2.0.4
  shimmer: ^2.0.0
  storage_space: ^1.0.1+5
  store_redirect: ^2.0.0
  syncfusion_flutter_datepicker: ^19.2.62
  syncfusion_flutter_gauges: ^19.2.62

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
