class Country {
  final String name;
  final String flag;
  final String code;
  final String phoneCode;

  Country({required this.name, required this.flag, required this.code, required this.phoneCode});
}

class CountryCodeList {
  static final CountryCodeList _instance = CountryCodeList._internal();

  factory CountryCodeList() => _instance;

  CountryCodeList._internal();

  static final List<Country> countries = [
    Country(
      name: "Afghanistan",
      flag: "🇦🇫",
      code: "AF",
      phoneCode: "+93",
    ),
    Country(
      name: "Åland Islands",
      flag: "🇦🇽",
      code: "AX",
      phoneCode: "+358",
    ),
    Country(
      name: "Albania",
      flag: "🇦🇱",
      code: "AL",
      phoneCode: "+355",
    ),
    Country(
      name: "Algeria",
      flag: "🇩🇿",
      code: "DZ",
      phoneCode: "+213",
    ),
    Country(
      name: "American Samoa",
      flag: "🇦🇸",
      code: "AS",
      phoneCode: "+1684",
    ),
    Country(
      name: "Andorra",
      flag: "🇦🇩",
      code: "AD",
      phoneCode: "+376",
    ),
    Country(
      name: "Angola",
      flag: "🇦🇴",
      code: "AO",
      phoneCode: "+244",
    ),
    Country(
      name: "Anguilla",
      flag: "🇦🇮",
      code: "AI",
      phoneCode: "+1264",
    ),
    Country(
      name: "Antarctica",
      flag: "🇦🇶",
      code: "AQ",
      phoneCode: "+672",
    ),
    Country(
      name: "Antigua and Barbuda",
      flag: "🇦🇬",
      code: "AG",
      phoneCode: "+1268",
    ),
    Country(
      name: "Argentina",
      flag: "🇦🇷",
      code: "AR",
      phoneCode: "+54",
    ),
    Country(
      name: "Armenia",
      flag: "🇦🇲",
      code: "AM",
      phoneCode: "+374",
    ),
    Country(
      name: "Aruba",
      flag: "🇦🇼",
      code: "AW",
      phoneCode: "+297",
    ),
    Country(
      name: "Australia",
      flag: "🇦🇺",
      code: "AU",
      phoneCode: "+61",
    ),
    Country(
      name: "Austria",
      flag: "🇦🇹",
      code: "AT",
      phoneCode: "+43",
    ),
    Country(
      name: "Azerbaijan",
      flag: "🇦🇿",
      code: "AZ",
      phoneCode: "+994",
    ),
    Country(
      name: "Bahamas",
      flag: "🇧🇸",
      code: "BS",
      phoneCode: "+1242",
    ),
    Country(
      name: "Bahrain",
      flag: "🇧🇭",
      code: "BH",
      phoneCode: "+973",
    ),
    Country(
      name: "Bangladesh",
      flag: "🇧🇩",
      code: "BD",
      phoneCode: "+880",
    ),
    Country(
      name: "Barbados",
      flag: "🇧🇧",
      code: "BB",
      phoneCode: "+1246",
    ),
    Country(
      name: "Belarus",
      flag: "🇧🇾",
      code: "BY",
      phoneCode: "+375",
    ),
    Country(
      name: "Belgium",
      flag: "🇧🇪",
      code: "BE",
      phoneCode: "+32",
    ),
    Country(
      name: "Belize",
      flag: "🇧🇿",
      code: "BZ",
      phoneCode: "+501",
    ),
    Country(
      name: "Benin",
      flag: "🇧🇯",
      code: "BJ",
      phoneCode: "+229",
    ),
    Country(
      name: "Bermuda",
      flag: "🇧🇲",
      code: "BM",
      phoneCode: "+1441",
    ),
    Country(
      name: "Bhutan",
      flag: "🇧🇹",
      code: "BT",
      phoneCode: "+975",
    ),
    Country(
      name: "Bolivia",
      flag: "🇧🇴",
      code: "BO",
      phoneCode: "+591",
    ),
    Country(
      name: "Bosnia and Herzegovina",
      flag: "🇧🇦",
      code: "BA",
      phoneCode: "+387",
    ),
    Country(
      name: "Botswana",
      flag: "🇧🇼",
      code: "BW",
      phoneCode: "+267",
    ),
    Country(
      name: "Bouvet Island",
      flag: "🇧🇻",
      code: "BV",
      phoneCode: "+47",
    ),
    Country(
      name: "Brazil",
      flag: "🇧🇷",
      code: "BR",
      phoneCode: "+55",
    ),
    Country(
      name: "British Indian Ocean Territory",
      flag: "🇮🇴",
      code: "IO",
      phoneCode: "+246",
    ),
    Country(
      name: "Brunei Darussalam",
      flag: "🇧🇳",
      code: "BN",
      phoneCode: "+673",
    ),
    Country(
      name: "Bulgaria",
      flag: "🇧🇬",
      code: "BG",
      phoneCode: "+359",
    ),
    Country(
      name: "Burkina Faso",
      flag: "🇧🇫",
      code: "BF",
      phoneCode: "+226",
    ),
    Country(
      name: "Burundi",
      flag: "🇧🇮",
      code: "BI",
      phoneCode: "+257",
    ),
    Country(
      name: "Cambodia",
      flag: "🇰🇭",
      code: "KH",
      phoneCode: "+855",
    ),
    Country(
      name: "Cameroon",
      flag: "🇨🇲",
      code: "CM",
      phoneCode: "+237",
    ),
    Country(
      name: "Canada",
      flag: "🇨🇦",
      code: "CA",
      phoneCode: "+1",
    ),
    Country(
      name: "Cape Verde",
      flag: "🇨🇻",
      code: "CV",
      phoneCode: "+238",
    ),
    Country(
      name: "Cayman Islands",
      flag: "🇰🇾",
      code: "KY",
      phoneCode: "+345",
    ),
    Country(
      name: "Central African Republic",
      flag: "🇨🇫",
      code: "CF",
      phoneCode: "+236",
    ),
    Country(
      name: "Chad",
      flag: "🇹🇩",
      code: "TD",
      phoneCode: "+235",
    ),
    Country(
      name: "Chile",
      flag: "🇨🇱",
      code: "CL",
      phoneCode: "+56",
    ),
    Country(
      name: "China",
      flag: "🇨🇳",
      code: "CN",
      phoneCode: "+86",
    ),
    Country(
      name: "Christmas Island",
      flag: "🇨🇽",
      code: "CX",
      phoneCode: "+61",
    ),
    Country(
      name: "Cocos (Keeling) Islands",
      flag: "🇨🇨",
      code: "CC",
      phoneCode: "+61",
    ),
    Country(
      name: "Colombia",
      flag: "🇨🇴",
      code: "CO",
      phoneCode: "+57",
    ),
    Country(
      name: "Comoros",
      flag: "🇰🇲",
      code: "KM",
      phoneCode: "+269",
    ),
    Country(
      name: "Congo",
      flag: "🇨🇬",
      code: "CG",
      phoneCode: "+242",
    ),
    Country(
      name: "The Democratic Republic of the Congo",
      flag: "🇨🇩",
      code: "CD",
      phoneCode: "+243",
    ),
    Country(
      name: "Cook Islands",
      flag: "🇨🇰",
      code: "CK",
      phoneCode: "+682",
    ),
    Country(
      name: "Costa Rica",
      flag: "🇨🇷",
      code: "CR",
      phoneCode: "+506",
    ),
    Country(
      name: "Cote d'Ivoire",
      flag: "🇨🇮",
      code: "CI",
      phoneCode: "+225",
    ),
    Country(
      name: "Croatia",
      flag: "🇭🇷",
      code: "HR",
      phoneCode: "+385",
    ),
    Country(
      name: "Cuba",
      flag: "🇨🇺",
      code: "CU",
      phoneCode: "+53",
    ),
    Country(
      name: "Cyprus",
      flag: "🇨🇾",
      code: "CY",
      phoneCode: "+357",
    ),
    Country(
      name: "Czech Republic",
      flag: "🇨🇿",
      code: "CZ",
      phoneCode: "+420",
    ),
    Country(
      name: "Denmark",
      flag: "🇩🇰",
      code: "DK",
      phoneCode: "+45",
    ),
    Country(
      name: "Djibouti",
      flag: "🇩🇯",
      code: "DJ",
      phoneCode: "+253",
    ),
    Country(
      name: "Dominica",
      flag: "🇩🇲",
      code: "DM",
      phoneCode: "+1767",
    ),
    Country(
      name: "Dominican Republic",
      flag: "🇩🇴",
      code: "DO",
      phoneCode: "+1849",
    ),
    Country(
      name: "Ecuador",
      flag: "🇪🇨",
      code: "EC",
      phoneCode: "+593",
    ),
    Country(
      name: "Egypt",
      flag: "🇪🇬",
      code: "EG",
      phoneCode: "+20",
    ),
    Country(
      name: "El Salvador",
      flag: "🇸🇻",
      code: "SV",
      phoneCode: "+503",
    ),
    Country(
      name: "Equatorial Guinea",
      flag: "🇬🇶",
      code: "GQ",
      phoneCode: "+240",
    ),
    Country(
      name: "Eritrea",
      flag: "🇪🇷",
      code: "ER",
      phoneCode: "+291",
    ),
    Country(
      name: "Estonia",
      flag: "🇪🇪",
      code: "EE",
      phoneCode: "+372",
    ),
    Country(
      name: "Ethiopia",
      flag: "🇪🇹",
      code: "ET",
      phoneCode: "+251",
    ),
    Country(
      name: "Falkland Islands (Malvinas)",
      flag: "🇫🇰",
      code: "FK",
      phoneCode: "+500",
    ),
    Country(
      name: "Faroe Islands",
      flag: "🇫🇴",
      code: "FO",
      phoneCode: "+298",
    ),
    Country(
      name: "Fiji",
      flag: "🇫🇯",
      code: "FJ",
      phoneCode: "+679",
    ),
    Country(
      name: "Finland",
      flag: "🇫🇮",
      code: "FI",
      phoneCode: "+358",
    ),
    Country(
      name: "France",
      flag: "🇫🇷",
      code: "FR",
      phoneCode: "+33",
    ),
    Country(
      name: "French Guiana",
      flag: "🇬🇫",
      code: "GF",
      phoneCode: "+594",
    ),
    Country(
      name: "French Polynesia",
      flag: "🇵🇫",
      code: "PF",
      phoneCode: "+689",
    ),
    Country(
      name: "French Southern Territories",
      flag: "🇹🇫",
      code: "TF",
      phoneCode: "+262",
    ),
    Country(
      name: "Gabon",
      flag: "🇬🇦",
      code: "GA",
      phoneCode: "+241",
    ),
    Country(
      name: "Gambia",
      flag: "🇬🇲",
      code: "GM",
      phoneCode: "+220",
    ),
    Country(
      name: "Georgia",
      flag: "🇬🇪",
      code: "GE",
      phoneCode: "+995",
    ),
    Country(
      name: "Germany",
      flag: "🇩🇪",
      code: "DE",
      phoneCode: "+49",
    ),
    Country(
      name: "Ghana",
      flag: "🇬🇭",
      code: "GH",
      phoneCode: "+233",
    ),
    Country(
      name: "Gibraltar",
      flag: "🇬🇮",
      code: "GI",
      phoneCode: "+350",
    ),
    Country(
      name: "Greece",
      flag: "🇬🇷",
      code: "GR",
      phoneCode: "+30",
    ),
    Country(
      name: "Greenland",
      flag: "🇬🇱",
      code: "GL",
      phoneCode: "+299",
    ),
    Country(
      name: "Grenada",
      flag: "🇬🇩",
      code: "GD",
      phoneCode: "+1473",
    ),
    Country(
      name: "Guadeloupe",
      flag: "🇬🇵",
      code: "GP",
      phoneCode: "+590",
    ),
    Country(
      name: "Guam",
      flag: "🇬🇺",
      code: "GU",
      phoneCode: "+1671",
    ),
    Country(
      name: "Guatemala",
      flag: "🇬🇹",
      code: "GT",
      phoneCode: "+502",
    ),
    Country(
      name: "Guernsey",
      flag: "🇬🇬",
      code: "GG",
      phoneCode: "+44",
    ),
    Country(
      name: "Guinea",
      flag: "🇬🇳",
      code: "GN",
      phoneCode: "+224",
    ),
    Country(
      name: "Guinea-Bissau",
      flag: "🇬🇼",
      code: "GW",
      phoneCode: "+245",
    ),
    Country(
      name: "Guyana",
      flag: "🇬🇾",
      code: "GY",
      phoneCode: "+592",
    ),
    Country(
      name: "Haiti",
      flag: "🇭🇹",
      code: "HT",
      phoneCode: "+509",
    ),
    Country(
      name: "Holy See (Vatican City State)",
      flag: "🇻🇦",
      code: "VA",
      phoneCode: "+379",
    ),
    Country(
      name: "Honduras",
      flag: "🇭🇳",
      code: "HN",
      phoneCode: "+504",
    ),
    Country(
      name: "Hong Kong",
      flag: "🇭🇰",
      code: "HK",
      phoneCode: "+852",
    ),
    Country(
      name: "Hungary",
      flag: "🇭🇺",
      code: "HU",
      phoneCode: "+36",
    ),
    Country(
      name: "Iceland",
      flag: "🇮🇸",
      code: "IS",
      phoneCode: "+354",
    ),
    Country(
      name: "India",
      flag: "🇮🇳",
      code: "IN",
      phoneCode: "+91",
    ),
    Country(
      name: "Indonesia",
      flag: "🇮🇩",
      code: "ID",
      phoneCode: "+62",
    ),
    Country(
      name: "Iran",
      flag: "🇮🇷",
      code: "IR",
      phoneCode: "+98",
    ),
    Country(
      name: "Iraq",
      flag: "🇮🇶",
      code: "IQ",
      phoneCode: "+964",
    ),
    Country(
      name: "Ireland",
      flag: "🇮🇪",
      code: "IE",
      phoneCode: "+353",
    ),
    Country(
      name: "Isle of Man",
      flag: "🇮🇲",
      code: "IM",
      phoneCode: "+44",
    ),
    Country(
      name: "Israel",
      flag: "🇮🇱",
      code: "IL",
      phoneCode: "+972",
    ),
    Country(
      name: "Italy",
      flag: "🇮🇹",
      code: "IT",
      phoneCode: "+39",
    ),
    Country(
      name: "Jamaica",
      flag: "🇯🇲",
      code: "JM",
      phoneCode: "+1876",
    ),
    Country(
      name: "Japan",
      flag: "🇯🇵",
      code: "JP",
      phoneCode: "+81",
    ),
    Country(
      name: "Jersey",
      flag: "🇯🇪",
      code: "JE",
      phoneCode: "+44",
    ),
    Country(
      name: "Jordan",
      flag: "🇯🇴",
      code: "JO",
      phoneCode: "+962",
    ),
    Country(
      name: "Kazakhstan",
      flag: "🇰🇿",
      code: "KZ",
      phoneCode: "+7",
    ),
    Country(
      name: "Kenya",
      flag: "🇰🇪",
      code: "KE",
      phoneCode: "+254",
    ),
    Country(
      name: "Kiribati",
      flag: "🇰🇮",
      code: "KI",
      phoneCode: "+686",
    ),
    Country(
      name: "North Korea",
      flag: "🇰🇵",
      code: "KP",
      phoneCode: "+850",
    ),
    Country(
      name: "South Korea",
      flag: "🇰🇷",
      code: "KR",
      phoneCode: "+82",
    ),
    Country(
      name: "Kosovo",
      flag: "🇽🇰",
      code: "XK",
      phoneCode: "+383",
    ),
    Country(
      name: "Kuwait",
      flag: "🇰🇼",
      code: "KW",
      phoneCode: "+965",
    ),
    Country(
      name: "Kyrgyzstan",
      flag: "🇰🇬",
      code: "KG",
      phoneCode: "+996",
    ),
    Country(
      name: "Laos",
      flag: "🇱🇦",
      code: "LA",
      phoneCode: "+856",
    ),
    Country(
      name: "Latvia",
      flag: "🇱🇻",
      code: "LV",
      phoneCode: "+371",
    ),
    Country(
      name: "Lebanon",
      flag: "🇱🇧",
      code: "LB",
      phoneCode: "+961",
    ),
    Country(
      name: "Lesotho",
      flag: "🇱🇸",
      code: "LS",
      phoneCode: "+266",
    ),
    Country(
      name: "Liberia",
      flag: "🇱🇷",
      code: "LR",
      phoneCode: "+231",
    ),
    Country(
      name: "Libyan Arab Jamahiriya",
      flag: "🇱🇾",
      code: "LY",
      phoneCode: "+218",
    ),
    Country(
      name: "Liechtenstein",
      flag: "🇱🇮",
      code: "LI",
      phoneCode: "+423",
    ),
    Country(
      name: "Lithuania",
      flag: "🇱🇹",
      code: "LT",
      phoneCode: "+370",
    ),
    Country(
      name: "Luxembourg",
      flag: "🇱🇺",
      code: "LU",
      phoneCode: "+352",
    ),
    Country(
      name: "Macao",
      flag: "🇲🇴",
      code: "MO",
      phoneCode: "+853",
    ),
    Country(
      name: "Macedonia",
      flag: "🇲🇰",
      code: "MK",
      phoneCode: "+389",
    ),
    Country(
      name: "Madagascar",
      flag: "🇲🇬",
      code: "MG",
      phoneCode: "+261",
    ),
    Country(
      name: "Malawi",
      flag: "🇲🇼",
      code: "MW",
      phoneCode: "+265",
    ),
    Country(
      name: "Malaysia",
      flag: "🇲🇾",
      code: "MY",
      phoneCode: "+60",
    ),
    Country(
      name: "Maldives",
      flag: "🇲🇻",
      code: "MV",
      phoneCode: "+960",
    ),
    Country(
      name: "Mali",
      flag: "🇲🇱",
      code: "ML",
      phoneCode: "+223",
    ),
    Country(
      name: "Malta",
      flag: "🇲🇹",
      code: "MT",
      phoneCode: "+356",
    ),
    Country(
      name: "Marshall Islands",
      flag: "🇲🇭",
      code: "MH",
      phoneCode: "+692",
    ),
    Country(
      name: "Martinique",
      flag: "🇲🇶",
      code: "MQ",
      phoneCode: "+596",
    ),
    Country(
      name: "Mauritania",
      flag: "🇲🇷",
      code: "MR",
      phoneCode: "+222",
    ),
    Country(
      name: "Mauritius",
      flag: "🇲🇺",
      code: "MU",
      phoneCode: "+230",
    ),
    Country(
      name: "Mayotte",
      flag: "🇾🇹",
      code: "YT",
      phoneCode: "+262",
    ),
    Country(
      name: "Mexico",
      flag: "🇲🇽",
      code: "MX",
      phoneCode: "+52",
    ),
    Country(
      name: "Micronesia",
      flag: "🇫🇲",
      code: "FM",
      phoneCode: "+691",
    ),
    Country(
      name: "Moldova",
      flag: "🇲🇩",
      code: "MD",
      phoneCode: "+373",
    ),
    Country(
      name: "Monaco",
      flag: "🇲🇨",
      code: "MC",
      phoneCode: "+377",
    ),
    Country(
      name: "Mongolia",
      flag: "🇲🇳",
      code: "MN",
      phoneCode: "+976",
    ),
    Country(
      name: "Montenegro",
      flag: "🇲🇪",
      code: "ME",
      phoneCode: "+382",
    ),
    Country(
      name: "Montserrat",
      flag: "🇲🇸",
      code: "MS",
      phoneCode: "+1664",
    ),
    Country(
      name: "Morocco",
      flag: "🇲🇦",
      code: "MA",
      phoneCode: "+212",
    ),
    Country(
      name: "Mozambique",
      flag: "🇲🇿",
      code: "MZ",
      phoneCode: "+258",
    ),
    Country(
      name: "Myanmar",
      flag: "🇲🇲",
      code: "MM",
      phoneCode: "+95",
    ),
    Country(
      name: "Namibia",
      flag: "🇳🇦",
      code: "NA",
      phoneCode: "+264",
    ),
    Country(
      name: "Nauru",
      flag: "🇳🇷",
      code: "NR",
      phoneCode: "+674",
    ),
    Country(
      name: "Nepal",
      flag: "🇳🇵",
      code: "NP",
      phoneCode: "+977",
    ),
    Country(
      name: "Netherlands",
      flag: "🇳🇱",
      code: "NL",
      phoneCode: "+31",
    ),
    Country(
      name: "Netherlands Antilles",
      flag: "",
      code: "AN",
      phoneCode: "+599",
    ),
    Country(
      name: "New Caledonia",
      flag: "🇳🇨",
      code: "NC",
      phoneCode: "+687",
    ),
    Country(
      name: "New Zealand",
      flag: "🇳🇿",
      code: "NZ",
      phoneCode: "+64",
    ),
    Country(
      name: "Nicaragua",
      flag: "🇳🇮",
      code: "NI",
      phoneCode: "+505",
    ),
    Country(
      name: "Niger",
      flag: "🇳🇪",
      code: "NE",
      phoneCode: "+227",
    ),
    Country(
      name: "Nigeria",
      flag: "🇳🇬",
      code: "NG",
      phoneCode: "+234",
    ),
    Country(
      name: "Niue",
      flag: "🇳🇺",
      code: "NU",
      phoneCode: "+683",
    ),
    Country(
      name: "Norfolk Island",
      flag: "🇳🇫",
      code: "NF",
      phoneCode: "+672",
    ),
    Country(
      name: "Northern Mariana Islands",
      flag: "🇲🇵",
      code: "MP",
      phoneCode: "+1670",
    ),
    Country(
      name: "Norway",
      flag: "🇳🇴",
      code: "NO",
      phoneCode: "+47",
    ),
    Country(
      name: "Oman",
      flag: "🇴🇲",
      code: "OM",
      phoneCode: "+968",
    ),
    Country(
      name: "Pakistan",
      flag: "🇵🇰",
      code: "PK",
      phoneCode: "+92",
    ),
    Country(
      name: "Palau",
      flag: "🇵🇼",
      code: "PW",
      phoneCode: "+680",
    ),
    Country(
      name: "Palestinian Territory, Occupied",
      flag: "🇵🇸",
      code: "PS",
      phoneCode: "+970",
    ),
    Country(
      name: "Panama",
      flag: "🇵🇦",
      code: "PA",
      phoneCode: "+507",
    ),
    Country(
      name: "Papua New Guinea",
      flag: "🇵🇬",
      code: "PG",
      phoneCode: "+675",
    ),
    Country(
      name: "Paraguay",
      flag: "🇵🇾",
      code: "PY",
      phoneCode: "+595",
    ),
    Country(
      name: "Peru",
      flag: "🇵🇪",
      code: "PE",
      phoneCode: "+51",
    ),
    Country(
      name: "Philippines",
      flag: "🇵🇭",
      code: "PH",
      phoneCode: "+63",
    ),
    Country(
      name: "Pitcairn",
      flag: "🇵🇳",
      code: "PN",
      phoneCode: "+64",
    ),
    Country(
      name: "Poland",
      flag: "🇵🇱",
      code: "PL",
      phoneCode: "+48",
    ),
    Country(
      name: "Portugal",
      flag: "🇵🇹",
      code: "PT",
      phoneCode: "+351",
    ),
    Country(
      name: "Puerto Rico",
      flag: "🇵🇷",
      code: "PR",
      phoneCode: "+1939",
    ),
    Country(
      name: "Qatar",
      flag: "🇶🇦",
      code: "QA",
      phoneCode: "+974",
    ),
    Country(
      name: "Romania",
      flag: "🇷🇴",
      code: "RO",
      phoneCode: "+40",
    ),
    Country(
      name: "Russia",
      flag: "🇷🇺",
      code: "RU",
      phoneCode: "+7",
    ),
    Country(
      name: "Rwanda",
      flag: "🇷🇼",
      code: "RW",
      phoneCode: "+250",
    ),
    Country(
      name: "Reunion",
      flag: "🇷🇪",
      code: "RE",
      phoneCode: "+262",
    ),
    Country(
      name: "Saint Barthelemy",
      flag: "🇧🇱",
      code: "BL",
      phoneCode: "+590",
    ),
    Country(
      name: "Saint Helena",
      flag: "🇸🇭",
      code: "SH",
      phoneCode: "+290",
    ),
    Country(
      name: "Saint Kitts and Nevis",
      flag: "🇰🇳",
      code: "KN",
      phoneCode: "+1869",
    ),
    Country(
      name: "Saint Lucia",
      flag: "🇱🇨",
      code: "LC",
      phoneCode: "+1758",
    ),
    Country(
      name: "Saint Martin",
      flag: "🇲🇫",
      code: "MF",
      phoneCode: "+590",
    ),
    Country(
      name: "Saint Pierre and Miquelon",
      flag: "🇵🇲",
      code: "PM",
      phoneCode: "+508",
    ),
    Country(
      name: "Saint Vincent and the Grenadines",
      flag: "🇻🇨",
      code: "VC",
      phoneCode: "+1784",
    ),
    Country(
      name: "Samoa",
      flag: "🇼🇸",
      code: "WS",
      phoneCode: "+685",
    ),
    Country(
      name: "San Marino",
      flag: "🇸🇲",
      code: "SM",
      phoneCode: "+378",
    ),
    Country(
      name: "Sao Tome and Principe",
      flag: "🇸🇹",
      code: "ST",
      phoneCode: "+239",
    ),
    Country(
      name: "Saudi Arabia",
      flag: "🇸🇦",
      code: "SA",
      phoneCode: "+966",
    ),
    Country(
      name: "Senegal",
      flag: "🇸🇳",
      code: "SN",
      phoneCode: "+221",
    ),
    Country(
      name: "Serbia",
      flag: "🇷🇸",
      code: "RS",
      phoneCode: "+381",
    ),
    Country(
      name: "Seychelles",
      flag: "🇸🇨",
      code: "SC",
      phoneCode: "+248",
    ),
    Country(
      name: "Sierra Leone",
      flag: "🇸🇱",
      code: "SL",
      phoneCode: "+232",
    ),
    Country(
      name: "Singapore",
      flag: "🇸🇬",
      code: "SG",
      phoneCode: "+65",
    ),
    Country(
      name: "Slovakia",
      flag: "🇸🇰",
      code: "SK",
      phoneCode: "+421",
    ),
    Country(
      name: "Slovenia",
      flag: "🇸🇮",
      code: "SI",
      phoneCode: "+386",
    ),
    Country(
      name: "Solomon Islands",
      flag: "🇸🇧",
      code: "SB",
      phoneCode: "+677",
    ),
    Country(
      name: "Somalia",
      flag: "🇸🇴",
      code: "SO",
      phoneCode: "+252",
    ),
    Country(
      name: "South Africa",
      flag: "🇿🇦",
      code: "ZA",
      phoneCode: "+27",
    ),
    Country(
      name: "South Sudan",
      flag: "🇸🇸",
      code: "SS",
      phoneCode: "+211",
    ),
    Country(
      name: "Spain",
      flag: "🇪🇸",
      code: "ES",
      phoneCode: "+34",
    ),
    Country(
      name: "Sri Lanka",
      flag: "🇱🇰",
      code: "LK",
      phoneCode: "+94",
    ),
    Country(
      name: "Sudan",
      flag: "🇸🇩",
      code: "SD",
      phoneCode: "+249",
    ),
    Country(
      name: "Suriname",
      flag: "🇸🇷",
      code: "SR",
      phoneCode: "+597",
    ),
    Country(
      name: "Svalbard and Jan Mayen",
      flag: "🇸🇯",
      code: "SJ",
      phoneCode: "+47",
    ),
    Country(
      name: "Swaziland",
      flag: "🇸🇿",
      code: "SZ",
      phoneCode: "+268",
    ),
    Country(
      name: "Sweden",
      flag: "🇸🇪",
      code: "SE",
      phoneCode: "+46",
    ),
    Country(
      name: "Switzerland",
      flag: "🇨🇭",
      code: "CH",
      phoneCode: "+41",
    ),
    Country(
      name: "Syrian Arab Republic",
      flag: "🇸🇾",
      code: "SY",
      phoneCode: "+963",
    ),
    Country(
      name: "Taiwan",
      flag: "🇹🇼",
      code: "TW",
      phoneCode: "+886",
    ),
    Country(
      name: "Tajikistan",
      flag: "🇹🇯",
      code: "TJ",
      phoneCode: "+992",
    ),
    Country(
      name: "Tanzania",
      flag: "🇹🇿",
      code: "TZ",
      phoneCode: "+255",
    ),
    Country(
      name: "Thailand",
      flag: "🇹🇭",
      code: "TH",
      phoneCode: "+66",
    ),
    Country(
      name: "Timor-Leste",
      flag: "🇹🇱",
      code: "TL",
      phoneCode: "+670",
    ),
    Country(
      name: "Togo",
      flag: "🇹🇬",
      code: "TG",
      phoneCode: "+228",
    ),
    Country(
      name: "Tokelau",
      flag: "🇹🇰",
      code: "TK",
      phoneCode: "+690",
    ),
    Country(
      name: "Tonga",
      flag: "🇹🇴",
      code: "TO",
      phoneCode: "+676",
    ),
    Country(
      name: "Trinidad and Tobago",
      flag: "🇹🇹",
      code: "TT",
      phoneCode: "+1868",
    ),
    Country(
      name: "Tunisia",
      flag: "🇹🇳",
      code: "TN",
      phoneCode: "+216",
    ),
    Country(
      name: "Turkey",
      flag: "🇹🇷",
      code: "TR",
      phoneCode: "+90",
    ),
    Country(
      name: "Turkmenistan",
      flag: "🇹🇲",
      code: "TM",
      phoneCode: "+993",
    ),
    Country(
      name: "Turks and Caicos Islands",
      flag: "🇹🇨",
      code: "TC",
      phoneCode: "+1649",
    ),
    Country(
      name: "Tuvalu",
      flag: "🇹🇻",
      code: "TV",
      phoneCode: "+688",
    ),
    Country(
      name: "Uganda",
      flag: "🇺🇬",
      code: "UG",
      phoneCode: "+256",
    ),
    Country(
      name: "Ukraine",
      flag: "🇺🇦",
      code: "UA",
      phoneCode: "+380",
    ),
    Country(
      name: "United Arab Emirates",
      flag: "🇦🇪",
      code: "AE",
      phoneCode: "+971",
    ),
    Country(
      name: "United Kingdom",
      flag: "🇬🇧",
      code: "GB",
      phoneCode: "+44",
    ),
    Country(
      name: "United States",
      flag: "🇺🇸",
      code: "US",
      phoneCode: "+1",
    ),
    Country(
      name: "Uruguay",
      flag: "🇺🇾",
      code: "UY",
      phoneCode: "+598",
    ),
    Country(
      name: "Uzbekistan",
      flag: "🇺🇿",
      code: "UZ",
      phoneCode: "+998",
    ),
    Country(
      name: "Vanuatu",
      flag: "🇻🇺",
      code: "VU",
      phoneCode: "+678",
    ),
    Country(
      name: "Venezuela",
      flag: "🇻🇪",
      code: "VE",
      phoneCode: "+58",
    ),
    Country(
      name: "Vietnam",
      flag: "🇻🇳",
      code: "VN",
      phoneCode: "+84",
    ),
    Country(
      name: "Virgin Islands, British",
      flag: "🇻🇬",
      code: "VG",
      phoneCode: "+1284",
    ),
    Country(
      name: "Virgin Islands, U.S.",
      flag: "🇻🇮",
      code: "VI",
      phoneCode: "+1340",
    ),
    Country(
      name: "Wallis and Futuna",
      flag: "🇼🇫",
      code: "WF",
      phoneCode: "+681",
    ),
    Country(
      name: "Yemen",
      flag: "🇾🇪",
      code: "YE",
      phoneCode: "+967",
    ),
    Country(
      name: "Zambia",
      flag: "🇿🇲",
      code: "ZM",
      phoneCode: "+260",
    ),
    Country(
      name: "Zimbabwe",
      flag: "🇿🇼",
      code: "ZW",
      phoneCode: "+263",
    ),
  ];
}
