/// Flutter icons DrugIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DrugIcon
///      fonts:
///       - asset: fonts/DrugIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DrugIcon {
  DrugIcon._();

  static const _kFontFam = 'DrugIcon';
  static const _kFontPkg = null;

  static const IconData herbal = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicine = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oncology = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unani = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unani2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
